baseURL = "https://eartjanvier2021.uptime-formation.fr/"
title = "Formation Ansible"
languageCode = "fr-FR"
defaultContentLanguage = "fr"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= true

# Modifiez le thème pour qu'il soit utilisé par défaut à chaque génération de site.
theme = "hugo-theme-learn"

# Pour la fonctionnalité de recherche
[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
editURL = "https://github.com/e-lie/hugo_cursus_janvier2020"


# [menu.shortcuts]


[Languages]
    [Languages.fr]
        title = "Imaginaires techniques - Le medium informatique"
        weight = 2
        languageName = "Français"
        landingPageURL = "/fr"
        landingPageName = "<i class='fas fa-home'></i> Accueil"

    [Languages.zh]
        title = "计算机作为一种艺术媒介"
        weight = 3
        languageName = "简体中文"
        landingPageURL = "/zh"
        landingPageName = "<i class='fas fa-home'></i> 家"